version: '3.8'

services:
  jupyter:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "8888:8888"
      - "8503:8503"
    environment:
      PYTHONPATH: /workspace
